import { OnInit, ElementRef, OnChanges, SimpleChanges, EventEmitter } from '@angular/core';
import { PbdsDatavizService } from './dataviz.service';
import { IPbdsDatavizPie } from './dataviz.interfaces';
export declare class PbdsDatavizPieComponent implements OnInit, OnChanges {
    private _dataviz;
    private _element;
    chartClass: boolean;
    pieClass: boolean;
    data: Array<IPbdsDatavizPie>;
    width: number;
    type: 'pie' | 'donut';
    mono: boolean;
    tooltipFormatString: string;
    legendFormatString: string;
    hovered: EventEmitter<object>;
    clicked: EventEmitter<object>;
    private height;
    private chart;
    private margin;
    private colors;
    private colorRange;
    private arc;
    private arcZoom;
    private svg;
    private pie;
    private legend;
    private legendFormat;
    private innerRadius;
    private anglePad;
    private outerRadius;
    private paths;
    private tooltip;
    private tooltipFormat;
    constructor(_dataviz: PbdsDatavizService, _element: ElementRef);
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    private legendMouseOverFocus;
    private legendMouseOutBlur;
    private pathMouseOver;
    private pathMouseOut;
    private pathClick;
    private tooltipShow;
    private tooltipMove;
    private tooltipHide;
    private tooltipSetPosition;
}
